server:
  port: 8004
spring:
  application:
    name: service-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.37.35.73:3306/mall?userSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 20
    maxWait: 5000
    filters: stat,wall
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    username: hcon
    password: hconuser
mybatis:
  type-aliases-package: com.kunlun.entity
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
     cache-enabled: true
     mapUnderscoreToCamelCase: true
pagehelper:
  helper-dialect: mysql
  reasonable: false         #默认开启  true:页码小于1或者页码大于最大时返回 第一条或者最后一条
  support-methods-arguments: true
  params: count=countSql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka